# Generated by Django 4.1.1 on 2023-01-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('science', 'Science'), ('history', 'History'), ('biography', 'Biography'), ('literature', 'Literature'), ('law', 'Law')], default='science', max_length=30),
        ),
    ]
